In [76]:
import edgar
import pandas as pd
import requests
from bs4 import BeautifulSoup

edgar.download_index(dest='/Users/GAURANG/Desktop/Webscraping-Financial-Statement',user_agent='gujratigaurang@gmail.com',since_year= 2018, skip_all_present_except_last=False )

In [77]:

selectedcompany = 'Alphabet Inc.'
selectedreport = '10-Q'

csv = pd.read_csv('2019-QTR4.tsv', sep='\t', lineterminator='\n', names=None)

csv.columns.values[0] = 'Item'

companyreport = csv[(csv['Item'].str.contains(selectedcompany)) & (csv['Item'].str.contains(selectedreport))]

Filing = companyreport['Item'].str.split('|')
Filing = Filing.to_list()

for item in Filing[0]:
    if 'html' in item:
        report = item

url = 'https://www.sec.gov/Archives/' + report[:-2]

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

tables = soup.find_all( class_ = "tableFile")

df = pd.read_html(str(tables[0]))
document_index = df[0]
document_index = document_index.dropna()

document_name = document_index[document_index['Description'].str.contains(selectedreport)]
document_name = document_name['Document'].str.split(' ')
document_name = document_name[0][0]

report_formatted = report[:-2].replace('-', '').replace('index.htm','')
url = 'https://www.sec.gov/Archives/' + report_formatted + '/' + document_name

In [99]:
headers1 = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

tables = soup
df = pd.read_html(str(tables))

for item in df:
    BS = (item[0].str.contains('Retained') | item[0].str.contains('Total Assests'))
    if BS.any():
        Balance_Sheet = item

Balance_Sheet = Balance_Sheet.iloc[2:,[0,2,6]]

header = Balance_Sheet.iloc[0]
Balance_Sheet = Balance_Sheet[1:]

Balance_Sheet.columns = header

c:\Users\GAURANG\AppData\Local\Programs\Python\Python311\Lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

In [100]:
Balance_Sheet

2,NaN,"As of December 31, 2018","As of September 30, 2019"
3,NaN,NaN,(unaudited)
4,Assets,NaN,NaN
5,Current assets:,NaN,NaN
6,Cash and cash equivalents,16701,16032
7,Marketable securities,92439,105145
8,"Total cash, cash equivalents, and marketable s...",109140,121177
9,"Accounts receivable, net of allowance of $729 ...",20838,20889
10,"Income taxes receivable, net",355,192
11,Inventory,1107,1401
12,Other current assets,4236,4699
13,Total current assets,135676,148358
14,Non-marketable investments,13859,12488
15,Deferred income taxes,737,564
16,"Property and equipment, net",59719,69252
17,Operating lease assets,0,10341
18,"Intangible assets, net",2220,1747
19,Goodwill,17888,18069
20,Other non-current assets,2693,2225
21,Total assets,232792,263044
22,Liabilities and Stockholdersâ€™ Equity,NaN,NaN
23,Current liabilities:,NaN,NaN
24,Accounts payable,4378,4142
25,Accrued compensation and benefits,6839,7399
26,Accrued expenses and other current liabilities,16958,21038
27,Accrued revenue share,4592,4835
28,Deferred revenue,1784,1679
29,"Income taxes payable, net",69,131
30,Total current liabilities,34620,39224
31,Long-term debt,4012,4082
32,"Deferred revenue, non-current",396,364
33,"Income taxes payable, non-current",11327,11355
34,Deferred income taxes,1264,1747
35,Operating lease liabilities,0,9666
36,Other long-term liabilities,3545,1637
37,Total liabilities,55164,68075
38,Commitments and Contingencies (Note 10),NaN,NaN
39,Stockholdersâ€™ equity:,NaN,NaN
40,"Convertible preferred stock, $0.001 par value ...",0,0
41,"ClassÂ A and Class B common stock, and Class C ...",45049,49040
42,Accumulated other comprehensive loss,"(2,306","(1,196"
43,Retained earnings,134885,147125
44,Total stockholdersâ€™ equity,177628,194969
45,Total liabilities and stockholdersâ€™ equity,232792,263044

In [114]:
Balance_Sheet.columns.values[0] = 'Item'
Balance_Sheet

2,Item,"As of December 31, 2018","As of September 30, 2019"
6,Cash and cash equivalents,16701,16032
7,Marketable securities,92439,105145
8,"Total cash, cash equivalents, and marketable s...",109140,121177
9,"Accounts receivable, net of allowance of $729 ...",20838,20889
10,"Income taxes receivable, net",355,192
11,Inventory,1107,1401
12,Other current assets,4236,4699
13,Total current assets,135676,148358
14,Non-marketable investments,13859,12488
15,Deferred income taxes,737,564
16,"Property and equipment, net",59719,69252
17,Operating lease assets,0,10341
18,"Intangible assets, net",2220,1747
19,Goodwill,17888,18069
20,Other non-current assets,2693,2225
21,Total assets,232792,263044
24,Accounts payable,4378,4142
25,Accrued compensation and benefits,6839,7399
26,Accrued expenses and other current liabilities,16958,21038
27,Accrued revenue share,4592,4835
28,Deferred revenue,1784,1679
29,"Income taxes payable, net",69,131
30,Total current liabilities,34620,39224
31,Long-term debt,4012,4082
32,"Deferred revenue, non-current",396,364
33,"Income taxes payable, non-current",11327,11355
34,Deferred income taxes,1264,1747
35,Operating lease liabilities,0,9666
36,Other long-term liabilities,3545,1637
37,Total liabilities,55164,68075
40,"Convertible preferred stock, $0.001 par value ...",0,0
41,"ClassÂ A and Class B common stock, and Class C ...",45049,49040
42,Accumulated other comprehensive loss,"(2,306","(1,196"
43,Retained earnings,134885,147125
44,Total stockholdersâ€™ equity,177628,194969
45,Total liabilities and stockholdersâ€™ equity,232792,263044

In [117]:
Balance_Sheet[Balance_Sheet.columns[1:]] = Balance_Sheet[Balance_Sheet.columns[1:]].astype(str)
Balance_Sheet[Balance_Sheet.columns[1]] = Balance_Sheet[Balance_Sheet.columns[1]].map(lambda x: x.replace('(','-'))
Balance_Sheet[Balance_Sheet.columns[2]] = Balance_Sheet[Balance_Sheet.columns[2]].map(lambda x: x.replace('(','-'))

Balance_Sheet[Balance_Sheet.columns[1]] = Balance_Sheet[Balance_Sheet.columns[1]].map(lambda x: x.replace(',',''))
Balance_Sheet[Balance_Sheet.columns[2]] = Balance_Sheet[Balance_Sheet.columns[2]].map(lambda x: x.replace(',',''))

Balance_Sheet[Balance_Sheet.columns[1:]] = Balance_Sheet[Balance_Sheet.columns[1:]].astype(float)

Balance_Sheet

2,Item,"As of December 31, 2018","As of September 30, 2019"
6,Cash and cash equivalents,16701.0,16032.0
7,Marketable securities,92439.0,105145.0
8,"Total cash, cash equivalents, and marketable s...",109140.0,121177.0
9,"Accounts receivable, net of allowance of $729 ...",20838.0,20889.0
10,"Income taxes receivable, net",355.0,192.0
11,Inventory,1107.0,1401.0
12,Other current assets,4236.0,4699.0
13,Total current assets,135676.0,148358.0
14,Non-marketable investments,13859.0,12488.0
15,Deferred income taxes,737.0,564.0
16,"Property and equipment, net",59719.0,69252.0
17,Operating lease assets,0.0,10341.0
18,"Intangible assets, net",2220.0,1747.0
19,Goodwill,17888.0,18069.0
20,Other non-current assets,2693.0,2225.0
21,Total assets,232792.0,263044.0
24,Accounts payable,4378.0,4142.0
25,Accrued compensation and benefits,6839.0,7399.0
26,Accrued expenses and other current liabilities,16958.0,21038.0
27,Accrued revenue share,4592.0,4835.0
28,Deferred revenue,1784.0,1679.0
29,"Income taxes payable, net",69.0,131.0
30,Total current liabilities,34620.0,39224.0
31,Long-term debt,4012.0,4082.0
32,"Deferred revenue, non-current",396.0,364.0
33,"Income taxes payable, non-current",11327.0,11355.0
34,Deferred income taxes,1264.0,1747.0
35,Operating lease liabilities,0.0,9666.0
36,Other long-term liabilities,3545.0,1637.0
37,Total liabilities,55164.0,68075.0
40,"Convertible preferred stock, $0.001 par value ...",0.0,0.0
41,"ClassÂ A and Class B common stock, and Class C ...",45049.0,49040.0
42,Accumulated other comprehensive loss,-2306.0,-1196.0
43,Retained earnings,134885.0,147125.0
44,Total stockholdersâ€™ equity,177628.0,194969.0
45,Total liabilities and stockholdersâ€™ equity,232792.0,263044.0

In [118]:
type(Balance_Sheet)

pandas.core.frame.DataFrame

In [124]:
df = pd.DataFrame(Balance_Sheet)
df.to_csv(r'C:\Users\GAURANG\Desktop\Webscraping-Financial-Statement\file.csv')